### ISSUE TITLE
Utilize Plasmic Permissions/role-based access functionality 

### ISSUE THREAD

**Issue by Salamit** [CallumBoase/plasmic-supabase#16]
Plasmic has role-based access control to give permissions to users depending on their role. Is this something you have in mind to add?

**Comment by CallumBoase** [comment]
Hi @Salamit 
One of the major purposes of this repo is to create a convenient way to use Supabase Auth, without having to also use Plasmic Auth. This avoids running 2 auth systems in parallel.
Unfortunately, the role-based access control functionality you see in Plasmic Studio relies Plasmic Auth.
As a result, we don't have it in mind to add suport for Plasmic's role-based access control.

However, we do plan to make it more convenient to
* Specify which pages are login protected and which are public
* Create an easy method to limit pages based on roles defined in Supabase

We are open to any suggestions on the best way to tackle role based access control with Supabase and Plasmic (as long as it doesn't require running Plasmic Auth too)

Let me know if you have any further questions or thoughts too
