### ISSUE TITLE
Supabase Uppy Uploader doesn't work for Supabase projects hosted locally or with custom domain

### ISSUE THREAD

**Issue by ryanmouritz** [CallumBoase/plasmic-supabase#20]
**Description of issue**
The Supabase Uppy Uploader currently only works for Supabase projects in the Supabase SaaS offering with a supabase.co domain. It is:

- A common development workflow to host a local Supabase instance for development
- A common production configuration to configure Supabase to use a custom URL matching the website domain (e.g. to ensure email links are domain matched for spam filter happiness)

**Expected behaviour**
On typical upload/download/delete action the Supabase Uppy Uploader should attempt upload to the http://127.0.0.1:54321 API endpoint for local environments and the custom URL for implementation with custom URL configured.

**Replication steps**
Follow these steps to setup a local development environment for Supabase: https://supabase.com/docs/guides/cli/local-development
Instantiate, use and configure the Supabase Uppy Uploader as normal.

**Investigation**
With the NEXT_PUBLIC_SUPABASE_URL key in an env.local file set to http://127.0.0.1:54321 the Supabase Uppy Uploader attempts network calls to https://127.supabase.co/storage/v1/upload/resumable on upload type actions.

I can see the following lines in the index.tsx file which is the likely cause:

The URL is built dynamically upon initialisation based on a project ID.

```
export async function initUppy(
  supabaseProjectId: string,
  ...
) {
  ...
  const supabaseStorageURL = `https://${supabaseProjectId}.supabase.co/storage/v1/upload/resumable`;
  ...
}
```
 
The project id is extracted from the project URL configured in the NEXT_PUBLIC_SUPABASE_URL environment variable.
```
    useEffect(() => {
    ...
        const uppy = await initUppy(
          supabaseProjectId,
          token,
          process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
        )

        setUppy(uppy)

      });

    }, [reset])
```

 getSupabaseProjectIdFromUrl gets the project id from the URL as follows:
```
 export default function getSupabaseProjectIdFromUrl(url: string) {
  return url
    .split("//")[1]
    .split(".")[0];
}
```

**Comment by ryanmouritz** [comment]
@CallumBoase I can't see a reason why the Supabase ProjectID needs to be extracted from the URL. Could you advise if there was?

It appears it is extracted from the URL only to rebuild the URL again.
e.g.  `https://abcdefghijklmnopqrstuv.supabase.co` becomes `abcdefghijklmnopqrstuv `before becoming `https://abcdefghijklmnopqrstuv.supabase.co/storage/v1/upload/resumable`

Could we transform directly to the storage URL from the NEXT_PUBLIC_SUPABASE_URL?
e.g. `https://abcdefghijklmnopqrstuv.supabase.co` direct to `https://abcdefghijklmnopqrstuv.supabase.co/storage/v1/upload/resumable`

**Comment by CallumBoase** [comment]
@ryanmouritz I agree with your suggestion - no point extracting the ID just to rebuild it again. 
There was no reason - I missed the common base URL when originally developing the uploader

**Comment by ryanmouritz** [comment]
I have a working solution. I'll submit a PR today
